services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  web1: &web-service
    image: web
    build: .
    command: npm start
    depends_on:
      - db
    volumes:
      - .:/app
      - nm:/app/node_modules
  web2:
    <<: *web-service
  lb:
    image: caddy:2-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "3000:3000"
volumes:
  pg_data:
  nm:
