services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build: .
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - nm:/app/node_modules

volumes:
  pg_data:
  nm:
